// Created by Benjahmin Singh-Reynolds on 9/29/25.
#include "BinaryData.h"

// This translation unit intentionally defines no symbols.
// The actual binary data for LatoMedium_ttf and its size are generated by
// the JUCE Assets target (juce_add_binary_data) and linked in via libAssets.a.
// Our header (source/BinaryData.h) just provides extern declarations that
// match those generated symbols.


